package org.lemsml.gwtui.client.guilib;

public enum Action {
	ADD_COMMENT, ADD_INFO, APPROVE, BACK, BROWSE, CANCEL, CLOSE, DOWNLOAD, EDIT, EXPORT, FILES, 
	GO, HELP, HIDE_DETAILS, LOGIN, LOGOUT, NEW_PROJECT, NEXT, OK, PREVIOUS, SAVE, 
	SHOW_DETAILS, SUBMIT, UPLOAD, VIEW, OTHER, LOAD, PREVIEW, RESET, REMOVE, RENAME, 
	DELETE, PLUS, DETAILS, X, APPLY, MOVE, ADD_MESSAGE, ADD_ELEMENT, SELECT, VIEW_PROPERTIES, 
	TOGGLE, CONFIRM, SEND, ADDTO_PROJECT, DEFINE, REVIEW, EXPORT_EXCEL, FILTER, CLEAR, PLAYVIDEO, SELECT_ALL, RUN
}
